### ISSUE TITLE
Error message troubleshooting.

### ISSUE THREAD

**Issue by Tigercardell** [openbermuda/karmapi#12]
I figured it may be a good idea to open an issue thread for error message stack traces.

**Comment by Tigercardell** [comment]
$ python -m karmapi.currie
Traceback (most recent call last):
  File "C:\Users\Gina\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Gina\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gina\devel\windowskarmapi\karmapi\karmapi\currie.py", line 17, in <module>
    import curio
  File "c:\users\gina\devel\curio\curio\__init__.py", line 6, in <module>
    from .task import *
  File "c:\users\gina\devel\curio\curio\task.py", line 578, in <module>
    from . import queue
  File "c:\users\gina\devel\curio\curio\queue.py", line 18, in <module>
    from . import workers
  File "c:\users\gina\devel\curio\curio\workers.py", line 19, in <module>
    from .channel import Channel
  File "c:\users\gina\devel\curio\curio\channel.py", line 14, in <module>
    from . import socket
  File "c:\users\gina\devel\curio\curio\socket.py", line 20, in <module>
    from . import io
ValueError: source code string cannot contain null bytes

Trying to run currie on the windows side with git bash. I have no idea what this is saying.

**Comment by swfiua** [comment]
Looks like a corrupt curio.

What happens if you just "import curio"  at a python prompt?

What does git status say in the curio folder?

**Comment by Tigercardell** [comment]
>>> import curio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\gina\devel\curio\curio\__init__.py", line 6, in <module>
    from .task import *
  File "c:\users\gina\devel\curio\curio\task.py", line 578, in <module>
    from . import queue
  File "c:\users\gina\devel\curio\curio\queue.py", line 18, in <module>
    from . import workers
  File "c:\users\gina\devel\curio\curio\workers.py", line 19, in <module>
    from .channel import Channel
  File "c:\users\gina\devel\curio\curio\channel.py", line 14, in <module>
    from . import socket
  File "c:\users\gina\devel\curio\curio\socket.py", line 20, in <module>
    from . import io
ValueError: source code string cannot contain null bytes

looks like you're right, exact same error.

**Comment by Tigercardell** [comment]
what do i have to do to fix that

**Comment by Tigercardell** [comment]
oh, and this is the git status:

$ git status
On branch master
Your branch is ahead of 'origin/master' by 17 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        curio.egg-info/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by Ka1lon** [comment]
hey send me that contact list for those guys plz

**Comment by swfiua** [comment]
I was hoping git status would report io.py had been modified and a mysterious "null byte" added to it, but the only change is in curio.egg-info/ which I think gets created when you install curio.

It does seem odd that "Your branch is ahead of 'origin/master by 17 commits"  -- what is origin master set to?

At this point may be best just go delete the whole thing, do a fresh git clone and install.

**Comment by Tigercardell** [comment]
Should I do a git clone or a pip install, considering I'm not planning to mess with curio code?

**Comment by swfiua** [comment]
I think you answered your own question.

Pip install should be good.

The only gotcha is I'm not sure which version wins if you have previously
reported installed in a different way.

**Comment by Tigercardell** [comment]
after deleting my curio folder and pip installing curio (it ended up being curio 0.6):

Traceback (most recent call last):
  File "C:\Users\Gina\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Gina\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\gina\devel\windowskarmapi\karmapi\karmapi\currie.py", line 19, in <module>
    from karmapi import hush
  File "c:\users\gina\devel\windowskarmapi\karmapi\karmapi\hush.py", line 24, in <module>
    from matplotlib import pyplot
  File "C:\Users\Gina\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "C:\Users\Gina\Anaconda3\lib\site-packages\matplotlib\cbook.py", line 33, in <module>
    import numpy as np
  File "C:\Users\Gina\Anaconda3\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Users\Gina\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Gina\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\Gina\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Gina\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

**Comment by swfiua** [comment]
So now you have a broken numpy.

Wondering if this is something connected to moving to python 3.6

**Comment by swfiua** [comment]
Tiger:

Not sure what is going on there.   To be honest, it looks like something is corrupted on your disk.

The "ValueError: source code string cannot contain null bytes"  error is something I have never seen before.

A null byte is a byte where all the bits are zero.    Often files on disk are padded with zeroes up to the next sector boundary.   So if the operating system has its file directory corrupted it might read a longer file and pick up some nulls at the end of the file.

More likely if you press "Control-space".  emacs shows these as C-@ or something like that.

Anyway.. I am going to write a test for this, could be interesting and about time karmapi grew some tests.

Related to the nulls a hash function called SHA-1 has been in the news.   Someone has constructed a collision, two pdf documents that give the same hash function. 

Linus also had something to say on how this affects git -- which uses SHA-1.   The worry there is someone could sneak in a modified version of your code and you not notice it.

The piece from Linus was a good read.

**Comment by swfiua** [comment]
oops -- didn't mean  to close this issue.  back open....
